/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedLookupRouteImport } from './routes/_authenticated/lookup'
import { Route as AuthenticatedHouseholdsRouteImport } from './routes/_authenticated/households'
import { Route as AuthenticatedGisRouteImport } from './routes/_authenticated/gis'
import { Route as AuthenticatedFarmersRouteImport } from './routes/_authenticated/farmers'
import { Route as AuthenticatedDistributionsRouteImport } from './routes/_authenticated/distributions'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFarmersNewRouteImport } from './routes/_authenticated/farmers.new'
import { Route as AuthenticatedFarmersFarmerIdRouteImport } from './routes/_authenticated/farmers.$farmerId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLookupRoute = AuthenticatedLookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHouseholdsRoute = AuthenticatedHouseholdsRouteImport.update({
  id: '/households',
  path: '/households',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGisRoute = AuthenticatedGisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFarmersRoute = AuthenticatedFarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDistributionsRoute =
  AuthenticatedDistributionsRouteImport.update({
    id: '/distributions',
    path: '/distributions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFarmersNewRoute = AuthenticatedFarmersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedFarmersRoute,
} as any)
const AuthenticatedFarmersFarmerIdRoute =
  AuthenticatedFarmersFarmerIdRouteImport.update({
    id: '/$farmerId',
    path: '/$farmerId',
    getParentRoute: () => AuthenticatedFarmersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distributions': typeof AuthenticatedDistributionsRoute
  '/farmers': typeof AuthenticatedFarmersRouteWithChildren
  '/gis': typeof AuthenticatedGisRoute
  '/households': typeof AuthenticatedHouseholdsRoute
  '/lookup': typeof AuthenticatedLookupRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/farmers/$farmerId': typeof AuthenticatedFarmersFarmerIdRoute
  '/farmers/new': typeof AuthenticatedFarmersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distributions': typeof AuthenticatedDistributionsRoute
  '/farmers': typeof AuthenticatedFarmersRouteWithChildren
  '/gis': typeof AuthenticatedGisRoute
  '/households': typeof AuthenticatedHouseholdsRoute
  '/lookup': typeof AuthenticatedLookupRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/farmers/$farmerId': typeof AuthenticatedFarmersFarmerIdRoute
  '/farmers/new': typeof AuthenticatedFarmersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/distributions': typeof AuthenticatedDistributionsRoute
  '/_authenticated/farmers': typeof AuthenticatedFarmersRouteWithChildren
  '/_authenticated/gis': typeof AuthenticatedGisRoute
  '/_authenticated/households': typeof AuthenticatedHouseholdsRoute
  '/_authenticated/lookup': typeof AuthenticatedLookupRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/_authenticated/farmers/$farmerId': typeof AuthenticatedFarmersFarmerIdRoute
  '/_authenticated/farmers/new': typeof AuthenticatedFarmersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/dashboard'
    | '/distributions'
    | '/farmers'
    | '/gis'
    | '/households'
    | '/lookup'
    | '/reports'
    | '/settings'
    | '/users'
    | '/warehouses'
    | '/farmers/$farmerId'
    | '/farmers/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/dashboard'
    | '/distributions'
    | '/farmers'
    | '/gis'
    | '/households'
    | '/lookup'
    | '/reports'
    | '/settings'
    | '/users'
    | '/warehouses'
    | '/farmers/$farmerId'
    | '/farmers/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/distributions'
    | '/_authenticated/farmers'
    | '/_authenticated/gis'
    | '/_authenticated/households'
    | '/_authenticated/lookup'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/warehouses'
    | '/_authenticated/farmers/$farmerId'
    | '/_authenticated/farmers/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lookup': {
      id: '/_authenticated/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof AuthenticatedLookupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/households': {
      id: '/_authenticated/households'
      path: '/households'
      fullPath: '/households'
      preLoaderRoute: typeof AuthenticatedHouseholdsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gis': {
      id: '/_authenticated/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof AuthenticatedGisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/farmers': {
      id: '/_authenticated/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof AuthenticatedFarmersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/distributions': {
      id: '/_authenticated/distributions'
      path: '/distributions'
      fullPath: '/distributions'
      preLoaderRoute: typeof AuthenticatedDistributionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/farmers/new': {
      id: '/_authenticated/farmers/new'
      path: '/new'
      fullPath: '/farmers/new'
      preLoaderRoute: typeof AuthenticatedFarmersNewRouteImport
      parentRoute: typeof AuthenticatedFarmersRoute
    }
    '/_authenticated/farmers/$farmerId': {
      id: '/_authenticated/farmers/$farmerId'
      path: '/$farmerId'
      fullPath: '/farmers/$farmerId'
      preLoaderRoute: typeof AuthenticatedFarmersFarmerIdRouteImport
      parentRoute: typeof AuthenticatedFarmersRoute
    }
  }
}

interface AuthenticatedFarmersRouteChildren {
  AuthenticatedFarmersFarmerIdRoute: typeof AuthenticatedFarmersFarmerIdRoute
  AuthenticatedFarmersNewRoute: typeof AuthenticatedFarmersNewRoute
}

const AuthenticatedFarmersRouteChildren: AuthenticatedFarmersRouteChildren = {
  AuthenticatedFarmersFarmerIdRoute: AuthenticatedFarmersFarmerIdRoute,
  AuthenticatedFarmersNewRoute: AuthenticatedFarmersNewRoute,
}

const AuthenticatedFarmersRouteWithChildren =
  AuthenticatedFarmersRoute._addFileChildren(AuthenticatedFarmersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistributionsRoute: typeof AuthenticatedDistributionsRoute
  AuthenticatedFarmersRoute: typeof AuthenticatedFarmersRouteWithChildren
  AuthenticatedGisRoute: typeof AuthenticatedGisRoute
  AuthenticatedHouseholdsRoute: typeof AuthenticatedHouseholdsRoute
  AuthenticatedLookupRoute: typeof AuthenticatedLookupRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistributionsRoute: AuthenticatedDistributionsRoute,
  AuthenticatedFarmersRoute: AuthenticatedFarmersRouteWithChildren,
  AuthenticatedGisRoute: AuthenticatedGisRoute,
  AuthenticatedHouseholdsRoute: AuthenticatedHouseholdsRoute,
  AuthenticatedLookupRoute: AuthenticatedLookupRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
